# Generated by Django 4.2.19 on 2025-02-26 14:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_professor_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='rating',
            field=models.FloatField(default=None, editable=False, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
