# Generated by Django 4.2.19 on 2025-02-26 16:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_moduleinstance_semester_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='rating',
            field=models.FloatField(default=None, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
