# Generated by Django 5.1.6 on 2025-02-26 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_module_id_remove_professor_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="module",
            name="code",
            field=models.CharField(
                editable=False, max_length=5, primary_key=True, serialize=False
            ),
        ),
    ]
