# Generated by Django 4.2.19 on 2025-02-26 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_module_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='code',
            field=models.CharField(editable=False, max_length=5, primary_key=True, serialize=False),
        ),
    ]
