# Generated by Django 4.2.19 on 2025-02-26 14:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_professor_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleinstance',
            name='semester',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(2)]),
        ),
        migrations.AddConstraint(
            model_name='moduleinstance',
            constraint=models.UniqueConstraint(fields=('module', 'year', 'semester'), name='unique_module_instance'),
        ),
        migrations.AddConstraint(
            model_name='professormodule',
            constraint=models.UniqueConstraint(fields=('professor', 'module_instance'), name='unique_professor_module'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('user', 'professor_module'), name='unique_rating'),
        ),
    ]
